### ISSUE TITLE
I'm not a piracy repo, don't want my name here

### ISSUE THREAD

**Issue by parrotgeek1** [xuac/warezz#60]
Please remove parrotgeek.com/repo from docs/software.md. not sure how it got there in the first place, everything on it is my own tweaks.

**Comment by xuac** [comment]
Sorry for that. you can remove it through a pr or I will do it when I get time.

I made this list by merging a few other lists so might have came from a list of cydia repos.

**Comment by parrotgeek1** [comment]
@xuac #65
